<?php
function vsystem_sync_user($tuser){
    global    $memcache;
    $get_result = $memcache->get('user:'.$tuser->name);
    $obj = json_decode($get_result);
    // cent 
    if ($obj){
	$bal = $memcache->get($tuser->name.':balance');
	$tuser->balance = $bal/100;
	$tuser->currency = $obj->currency;
	$tuser->lang = $obj->lang;
	$tuser->vuid = $obj->vuid;
	$tuser->ser = $obj->ser;
    }else{
	$tuser->notvalid = true;
    }
    return $tuser;
};

function vmember_perm() {
  return array('access member');
}

/**
 * Implementation of hook_menu().
 */
function vmember_menu() {
  global $user;
    $items['dashboard'] = array(
      'description' => 'Billing Service', 'title' => 'Dashboard',
      'menu_name' => 'features',
      'page callback' => 'vmember_rate_overview',
      'weight' => -8,
      'access arguments' => array('access member'),
      'type' => MENU_NORMAL_ITEM,
    );	
    $items['dashboard/rate'] = array(
      'description' => 'View Rate.', 'title' => 'Rate',
      'page callback' => 'vmember_rate_overview',
      'weight' => -9,
      'access arguments' => array('access member'),
      'type' => MENU_DEFAULT_LOCAL_TASK
    );	

    $items['dashboard/payment'] = array(
      'description' => 'Payment.', 'title' => 'Payment',
      'page callback' => 'vmember_detail',
      'weight' => -8,
      'access arguments' => array('access member'),
      'type' => MENU_LOCAL_TASK
    );	

    $items['dashboard/cdr'] = array(
      'description' => 'View CDR.', 'title' => 'CDR',
      'page callback' => 'vmember_cdr',
      'weight' => -8,
      'access arguments' => array('access member'),
      'type' => MENU_LOCAL_TASK
    );	

    $items['dashboard/topupmyaccount'] = array(
      'description' => 'TopUp.', 'title' => 'TopUP',
      'page callback' => 'vmember_topup_myaccount',
      'weight' => -8,
      'access arguments' => array('access member'),
      'type' => MENU_LOCAL_TASK
    );	

    $items['dashboard/transfer'] = array(
      'description' => 'Transfer.', 'title' => 'Transfer Money',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('vmember_topup_form'),
      'weight' => -8,
      'access arguments' => array('access member'),
      'type' => MENU_LOCAL_TASK
    );	
/*
    $items['user/%user/speeddial'] = array(
      'description' => 'Speed Dial.', 'title' => 'Speed Dial',
      'page callback' => 'vmember_speeddial',
      'weight' => -9,
      'access arguments' => array('access member'),
      'type' => MENU_LOCAL_TASK
    );	
    $items['user/%user/speeddial/delete'] = array(
	'title' => 'Delete Mobile',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('vmobile_speeddial_delete_confirm'),
        'access arguments' => array('access member'),
        'type' => MENU_CALLBACK
    );

    $items['user/%user/detail'] = array(
      'description' => 'View user detail.', 'title' => 'Detail',
      'page callback' => 'vmember_detail',
      'weight' => -8,
      'access arguments' => array('access member'),
      'type' => MENU_CALLBACK
    );	

    $items['user/%user/mobile'] = array(
      'description' => 'View user.', 'title' => 'Mobile Phone',
      'page callback' => 'vmobile_overview',
      'weight' => -9,
      'access arguments' => array('access member'),
	'type' => MENU_NORMAL_ITEM,
    );	

    $items['user/%user/mobile/list'] = array(
      'description' => 'My Mobile Phone.', 'title' => 'List',
      'page callback' => 'vmobile_overview',
      'weight' => -1,
      'access arguments' => array('access member'),
      'type' => MENU_DEFAULT_LOCAL_TASK
    );	

    $items['user/%user/mobile/add'] = array(
      'title' => 'Add',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('vmobile_form'),
      'access arguments' => array('access member'),
      'weight' => 0,
      'type' => MENU_LOCAL_TASK
      );
    $items['user/%user/mobile/edit'] = array(
      'description' => 'Mobile.', 'title' => 'Edit',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('vmobile_edit_form'),
      'weight' => 0,
      'access arguments' => array('access member'),
      'type' => MENU_CALLBACK
    );	

    $items['user/%user/mobile/cdr'] = array(
      'description' => 'View CDR.', 'title' => 'CDR',
      'page callback' => 'vmobile_cdr',
      'weight' => 5,
      'access arguments' => array('access member'),
      'type' => MENU_LOCAL_TASK,
    );	

    $items['user/%user/mobile/delete'] = array(
	'title' => 'Delete Mobile',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('vmobile_delete_confirm'),
        'access arguments' => array('access member'),
        'type' => MENU_CALLBACK
    );

    $items['user/'.$user->uid.'/wholesale'] = array(
      'description' => 'View user.', 'title' => 'WholeSale',
      'page callback' => 'vmember_prefix',
      'weight' => -13,
      'access arguments' => array('access member'),
	'type' => MENU_NORMAL_ITEM,
    );	
*/
  return $items;
}

function vmember_prefix() {
  global $user;
  $result = db_query("SELECT prefix from voipusers where name='%s' ",$user->name);
//  $result = db_fetch_object($result);

  $header = array(
    array('data' => t('Prefix'), 'field' => 'prefix')
  );

  while ($rate = db_fetch_object($result)) {
    $rows[] =
      array(
        // Cells
        $rate->prefix.'#',
	);
  }

  if (!$rows) {
    $rows[] = array(array('data' => t('Data Not Found.'), 'colspan' => 20));
  }

  $output .= theme('table', $header, $rows);
  $output .= theme('pager', NULL, 20, 0);

  return $output;
}


function vmobile_speeddial_delete_confirm($form_state,$id = NULL) {
    global $user;
    //echo $id;
    if (!$id)
            return drupal_goto('user/'.$user->uid.'/speeddial');
       
    $result = db_fetch_object(db_query("SELECT * from voip_speeddial WHERE id=%d ", $id,$user->vuid));

    if (!$result) {
	    drupal_set_message("SpeedDial ".$id." Not Found.",'error');
            return drupal_goto('user/'.$user->uid.'/speeddial');
    }

    $form['id'] = array('#type' => 'value', '#value' => $result->id);
    return confirm_form($form,
        t('Are you sure you want to delete %description?', array('%description' => $result->mobile)),
        $_GET['destination'] ? $_GET['destination'] : 'user/'.$user->uid.'/speeddial',
        t('This action cannot be undone.'),
        t('Delete'), t('Cancel')
    );
}

function vmobile_speeddial_delete_confirm_submit($form, &$form_state) {
    global $user;
    //print_r($form);
    if ($form_state['values']['confirm']) {
            db_query("DELETE FROM voip_speeddial WHERE id=%d ", $form_state['values']['id']);
    }
     //drupal_set_message("SpeedDial ".$form_state['values']['id']." Not Found.",'Deleted');
     return drupal_goto('user/'.$user->uid.'/speeddial');
}

function vmember_speeddial_form() {
						      
  $form['no'] = array(
    '#type' => 'textfield',
    '#title' => 'No',
    '#maxlength' => 2,
    '#size' => 2,
  );
  $form['number'] = array(
    '#type' => 'textfield',
    '#title' => 'Number',
    '#size' => 50,
  );
			
  $form['submit'] = array('#type' => 'submit', '#value' =>t('Add'));
//  $form['#redirect'] = FALSE;
  return $form;
}

function vmember_speeddial_form_submit($form, &$form_state) {
  global $user;
    if ( strlen($form_state['values']['no']) > 0 and strlen($form_state['values']['number']) >0)
         $result = db_query("INSERT into voip_speeddial(no,mobile,uid) Values('%s','%s',%d)",$form_state['values']['no'],$form_state['values']['number'],$user->uid);
    drupal_goto('user/'.$user->uid.'/speeddial');
}


function vmember_speeddial() {
  global $user;
  
  $output = drupal_get_form('vmember_speeddial_form');

  $header = array(
    array('data' => t('No.'), 'field' => 'no'),
    array('data' => t('Number'), 'field' => 'mobile'),
  );

  $tablesort = tablesort_sql($header);
  $sql = " SELECT * from voip_speeddial where uid=".$user->uid;
  $sql_count = "select count(id) from voip_speeddial where uid=".$user->uid;
  $result = pager_query($sql . $tablesort, 50,0,$sql_count);

  while ($rate = db_fetch_object($result)) {
    $rows[] =
      array(
        // Cells
        $rate->no,
        $rate->mobile,
	array('data' =>l('Del','user/'.$user->uid.'/speeddial/delete/'.$rate->id)),
	);
  }

  if (!$rows) {
    $rows[] = array(array('data' => t('Data Not Found.'), 'colspan' => 20));
  }

  $output .= theme('table', $header, $rows);
  $output .= theme('pager', NULL, 50, 0);

  return $output;
}

function vmember_form_overview() {
						      
  if (empty($_SESSION['vmember_search_filter'])) {
    $_SESSION['vmember_search_filter'] = '';
  }

  $form['search'] = array(
    '#type' => 'textfield',
    '#title' => 'Search',
    '#size' => 10,
    '#default_value' => $_SESSION['vmember_search_filter']
  );
			
  $form['submit'] = array('#type' => 'submit', '#value' =>t('Filter'));
//  $form['#redirect'] = FALSE;

  return $form;
}

function vmember_form_overview_submit($form, &$form_state) {
  $_SESSION['vmember_search_filter'] = $form_state['values']['search'];
}


function _vmember_get_vmember_group() {
  $types = array();

  $result = db_query('SELECT DISTINCT(description),id FROM voiptariffgrp ORDER BY description');
  while ($object = db_fetch_object($result)) {
    $types[] = array($object->id => $object->description);
  }

  return $types;
}

function vmember_form($id = NULL) {
  global $user;
  $user =  vsystem_sync_user($user);
  if ($id) {
    $result = db_query("SELECT * FROM dr_users  WHERE name = '%s'", $id);
    $card_lot = db_fetch_object($result);
    if (!$card_lot) {
      return drupal_goto('member');
    }
  }
  //check balance
  if ($user->balance <=0 ) {
      drupal_set_message("Credit not enough.Please Buy Credit Before Add member.",'error');
      return drupal_goto('dashboard');
  }
  
  $form['username'] = array(
    '#type' => 'textfield',
    '#title' => t("Username"),
    '#default_value' => $card_lot->name,
    '#maxlength' => 64,
    '#required' => true,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );


  return $form;
}

/**
 * Add/Edit bookmark form submit
 */
function vmember_form_submit($form, &$form_state) {
    global $user;
    $result = db_query("SELECT create_account_mobile_member('%s','%s');", $form['username'],$user->name);
    $card_lot = db_fetch_object($result);
    if ($card_lot) {
        if ($card_lot->create_account_mobile_member > 0 ) {
	    $_SESSION['vmember_search_filter'] = $form['username'];
	    drupal_set_message("Successfull Password is   '$card_lot->create_account_mobile_member' ");
	}else {
	    drupal_set_message("Create User ".$form['username']." Fail.",'error');
	};
    }
    return drupal_goto('member');
}

function vmember_topup_form($form_state = array(),$id = NULL) {
    global $user;
    $user =  vsystem_sync_user($user);
     if ($user->notvalid) {
      drupal_set_message("User  Not Found.",'error');
      return drupal_goto('dashboard/');
    };

      drupal_set_message("Your Balance :".$user->balance." ".$user->currency,'info');
      if ($user->balance<=0){
         drupal_set_message("Zero Balance Can't transfer");
         return drupal_goto('dashboard/payment');
      };	 
      
  $form['username'] = array(
    '#type' => 'textfield',
    '#title' => t("Transfer To User"),
    '#default_value' => $id,
    '#maxlength' => 25,
    '#required' => false
  );

  $form['amount'] = array(
    '#type' => 'textfield',
    '#title' => t("Amount"),
    '#default_value' => '0',
    '#maxlength' => 20,
    '#required' => false
  );

  $form['tsubmit'] = array(
    '#type' => 'submit',
    '#value' => 'Transfer',
  );

  return $form;
}

/**
 * Add/Edit bookmark form submit
 */
function vmember_topup_form_submit($form, &$form_state) {
  global $user;
  $user = vsystem_sync_user($user);
  
  if ((strlen($form_state['values']['username']) > 0) AND (strlen($form_state['values']['amount']) > 0) )
    if($user->balance > $form_state['values']['amount']){
     $result = db_query("SELECT a_i_pay('%s','%s',%d) As cpay ;", $user->name,$form_state['values']['username'],$form_state['values']['amount']*100);
     $card_lot = db_fetch_object($result);
     if (!$card_lot) {
      drupal_set_message("Transfer ".$form_state['values']['amount']." Fail.",'error');
         return drupal_goto('dashboard/payment');
     }else{
      if ($card_lot->cpay > 0) {
        drupal_set_message("Transfer ".$form_state['values']['amount']." Success.");
         return drupal_goto('dashboard/payment');
      }else{
        drupal_set_message("Transfer ".$form_state['values']['amount']." Fail. ".$card_lot->cpay,'error');
         return drupal_goto('dashboard/payment');
      };
    };  
  };
      
    drupal_set_message(" Credit not enough.",'error');
    return drupal_goto('dashboard');
    
}

function vmember_edit_form($id = NULL) {
    global $user;
    if (!$id) {
      return drupal_goto('user');
    }

    $sqlstr = "SELECT * FROM vuser1  WHERE username = '$id' and owner='$user->name'";
    $result = db_query($sqlstr);
    $card_lot = db_fetch_object($result);
  if (!$card_lot) {
      drupal_set_message("User ".$id." Not Found.",'error');
      //return $output;
      return drupal_goto('user');
  };

  $form['accountid'] = array(
    '#type' => 'textfield',
    '#title' => t("Account ID"),
    '#default_value' => $card_lot->accountid,
    '#required' => true,
    '#attributes' => array('readonly' => 'readonly'),
  );

  $form['username'] = array(
    '#type' => 'textfield',
    '#title' => t("Username"),
    '#default_value' => $card_lot->username,
    '#maxlength' => 255,
    '#required' => true,
    '#attributes' => array('readonly' => 'readonly'),
  );

  $form['secret'] = array(
    '#type' => 'textfield',
    '#title' => t("Password"),
    '#default_value' => $card_lot->secret,
    '#required' => true,
  );
  $form['balance'] = array(
    '#type' => 'textfield',
    '#title' => t("Balance"),
    '#default_value' => $card_lot->balance,
    '#required' => true,
    '#attributes' => array('readonly' => 'readonly'),
  );

  $types = array();
  $result = db_query('SELECT DISTINCT(description),id FROM voiptariffgrp where id = %d',$card_lot->grpid);
  while ($object = db_fetch_object($result)) {
    $names[$object->id] = $object->description;
  }
  $form['grpid'] = array(
    '#type' => 'select',
    '#title' => t("rate"),
    '#options' => $names,
    '#default_value' => $card_lot->grpid,
    '#required' => true,
    '#attributes' => array('readonly' => 'readonly'),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );


  return $form;
}

/**
 * Add/Edit bookmark form submit
 */
function vmember_edit_form_submit($form, &$form_state) {
  if ($form['accountid'] > 0)  {
//    $result = db_query("update voipusers set secret = '%s' where username = '%s';", $form['secret'],$form['username']);
    $result = db_query("update dr_users set plainpass = '%s',pass=MD5('%s') where name = '%s';", $form['secret'],$form['secret'],$form['username']);
    $card_lot = db_fetch_object($result);
    $result = db_query("update voiptariffsel set grpid = '%d' where accountid = '%d';", $form['grpid'],$form['accountid']);
    $card_lot = db_fetch_object($result);
  };    
    return drupal_goto('member');
}

function vmember_topup_myaccount_form() {
						      
  if (empty($_SESSION['vmember_search_filter'])) {
    $_SESSION['vmember_search_filter'] = '';
  }

  $form['tpin'] = array(
    '#type' => 'textfield',
    '#title' => 'Top UP From PIN',
    '#required' => true,
    '#size' => 50,
  );
			
  $form['submit'] = array('#type' => 'submit', '#value' =>t('Top UP'));
//  $form['#redirect'] = FALSE;
  return $form;
}

function vmember_topup_myaccount_form_submit($form, &$form_state) {
  global $user;
  if (strlen($form_state['values']['tpin']) > 0) {
    $result = db_query("SELECT a_card_pay('%s','%s') As cpay ;", $form_state['values']['tpin'],$user->name);
    $card_lot = db_fetch_object($result);
    if (!$card_lot) {
      drupal_set_message("TopUp From ".$form_state['values']['tpin']." Fail.",'error');
      return drupal_goto('dashboard');
    }else{
      if ($card_lot->cpay > 0) {
        drupal_set_message("TopUp From ".$form_state['values']['tpin']." Success.");
        return drupal_goto('dashboard');
      }else{
        drupal_set_message("TopUp From ".$form_state['values']['tpin']." Fail. ".$card_lot->cpay,'error');
        return drupal_goto('dashboard');
      };
    };  
  };
      
    drupal_set_message(" Fail.",'error');
    return drupal_goto('dashboard');
}


function vmember_rate_form_overview() {
						      
  if (empty($_SESSION['vmember_overview_filter'])) {
    $_SESSION['vmember_overview_filter'] = '0';
  }
  if (empty($_SESSION['vmember_search_filter'])) {
    $_SESSION['vmember_search_filter'] = '';
  }

  $form['search'] = array(
    '#type' => 'textfield',
    '#title' => 'Search',
    '#size' => 20,
    '#default_value' => $_SESSION['vmember_search_filter']
  );
			
  $form['submit'] = array('#type' => 'submit', '#value' =>t('Filter'));
//  $form['#redirect'] = FALSE;

  return $form;
}


//function vmember_rate_form_overview_submit($form_id, $form_values) {
//  $_SESSION['vmember_overview_filter'] = $form_values['filter'];
//  $_SESSION['vmember_search_filter'] = $form_values['search'];
//}

function vmember_rate_overview() {
  global $user;
  if (!$user->grpid){
    return drupal_goto('staff');
  };
//  print_r($user);
  $output = drupal_get_form('vmember_rate_form_overview');

  $header = array(
    array('data' => t('Destination'), 'field' => 'description'),
    array('data' => t('Prefix'), 'field' => 'prefix'),
    array('data' => t('Price'), 'field' => 'price'),
    array('data' => t('Currency'), 'field' => 'currencysym'),
    array('data' => t('Group'), 'field' => 'group_dsc'),
  );

  $tablesort = tablesort_sql($header);
  $type = $_SESSION['vmember_overview_filter'];
  $search_str = $_SESSION['vmember_search_filter'];
  $sql = "
   SELECT voiptariff.id, voiptariff.prefix, voiptariff.description, voiptariff.price, voiptariff.currencysym, voiptariff.grpid, voiptariffgrp.description AS group_dsc, voiptariffgrp.uid, voiptariff.initialincrement, voiptariff.regularincrement, voiptariff.graceperiod
   FROM voiptariff LEFT JOIN voiptariffgrp ON voiptariff.grpid = voiptariffgrp.id
  ";
  $sql_count = "select count(id) from voiptariff";
  $sql .= " WHERE grpid = $user->grpid ";
  $sql_count .= " WHERE grpid = $user->grpid ";
  //echo "S: ".$search_str;
  if ($search_str != '') {
    $sql .= " AND upper(voiptariff.description) LIKE upper('$search_str%') Or prefix LIKE '$search_str%' AND grpid = $user->grpid";
    $sql_count .= " AND upper(voiptariff.description) LIKE upper('$search_str%') Or prefix LIKE '$search_str%' AND grpid = $user->grpid";
  };
//echo $sql;
    $result = pager_query($sql . $tablesort, 50,0,$sql_count);

  while ($rate = db_fetch_object($result)) {
    $rows[] =
      array(
        // Cells
        $rate->description,
        $rate->prefix,
        ($rate->price)+($rate->price*$user->service_charge/100),
        $rate->currencysym,
        $rate->group_dsc,
    );
  }

  if (!$rows) {
    $rows[] = array(array('data' => t('Data Not Found.'), 'colspan' => 20));
  }

  $output .= theme('table', $header, $rows);
  $output .= theme('pager', NULL, 50, 0);

  return $output;
}

function vmember_rate_form_overview_submit($form, &$form_state) {
  $_SESSION['vmember_overview_filter'] = $form_state['values']['filter'];
  $_SESSION['vmember_search_filter'] = $form_state['values']['search'];
}

function vmember_detail($username = NULL) {
  global $user;
  $user = vsystem_sync_user($user);
  $output = 'Account :'.$user->name.'<br>'.'Balance :'.$user->balance.' '.$user->currencysym;
  $output .= '<br><br><b>Payment:</b><br>';
  $header = array(
//    array('data' => t('Username'), 'field' => 'username'),
    array('data' => t('Date'), 'field' => 'date','sort'=>'desc'),
    array('data' => t('Ref'), 'field' => 'ref'),
    array('data' => t('Amount'), 'field' => 'paid'),
  );
  if (!$username)
       $username = $user->name;
  $sql = "   SELECT *,date As cdate from vpayment where username='$username'   ";
  $sql_count = "select count(username) from vpayment where username='$username'";
  
  $tablesort = tablesort_sql($header);
  $result = pager_query($sql . $tablesort, 10,0,$sql_count);
  while ($rate = db_fetch_object($result)) {
    $rows[] =
      array(
        // Cells
 //       $rate->username,
        $rate->cdate,
        $rate->ref,
        number_format($rate->paid/100, 2, '.', ','),
    );
  }

  if (!$rows) {
    $rows[] = array(array('data' => t('Data Not Found.'), 'colspan' => 20));
  }

  $output .= theme('table', $header, $rows);
  $output .= theme('pager', NULL, 10, 0);

  return $output;
}

function vmember_cdr($username = NULL) {
  global $user;
  $user = vsystem_sync_user($user);
  
  $icons = array(WATCHDOG_NOTICE  => '',
                 WATCHDOG_WARNING => theme('image', 'misc/watchdog-warning.png', t('warning'), t('warning')),
                 WATCHDOG_ERROR   => theme('image', 'misc/watchdog-error.png', t('error'), t('error')));
  $classes = array(WATCHDOG_NOTICE => 'watchdog-notice', WATCHDOG_WARNING => 'watchdog-warning', WATCHDOG_ERROR => 'watchdog-error');

  if (strlen($username)==0)
    $username = $user->name;

  $output = 'Account :'.$username.'<br>'.'Balance :'.$user->balance.' '.$user->currencysym;
  $output .= '<br><br><b>Payment:</b><br>';

  $header = array(
    array('data' => t('Username'), 'field' => 'username'),
    array('data' => t('Date'), 'field' => 'acctstarttime','sort'=>'desc'),
    array('data' => t('Number'), 'field' => 'calledstationid'),
    array('data' => t('Destination'), 'field' => 'tariffdesc'),
    array('data' => t('Rate'), 'field' => 'price'),
    array('data' => t('Duration'), 'field' => 'duration'),
    array('data' => t('Total'), 'field' => 'cost'),
    array('data' => t('Currency'), 'field' => 'currencysym'),
  );
  $sql = " SELECT username,acctstarttime,calledstationid,tariffdesc,price,duration,
  cost,currencysym from voipcall Where username = '$username' ";

  $tablesort = tablesort_sql($header);
  $sql_count = "Select count(username) from voipcall Where username = '$username'";
  $result = pager_query($sql . $tablesort, 10,0,$sql_count);

  while ($rate = db_fetch_object($result)) {
    $rows[] =
      array(
        // Cells
        $rate->username,
        $rate->acctstarttime,
        $rate->calledstationid,
        $rate->tariffdesc,
        $rate->price,
        $rate->duration,
        $rate->cost,
        $rate->currencysym,
    );
  }

  if (!$rows) {
    $rows[] = array(array('data' => t('Data Not Found.'), 'colspan' => 20));
  }

  $output .= theme('table', $header, $rows);
  $output .= theme('pager', NULL, 10, 0);
  return $output;
}

function vmember_topup_myaccount() {
//  print l("hello dome",'?node/2');
  global $user;
  //http://221.128.124.203/callsbuy/admin/cart/add/destination=node/3
  $output = l('<img src="https://www.paypal.com/en_US/i/btn/x-click-butcc.gif">', "user/".$user->uid."/pay", array('absolute' => TRUE, 'html' => TRUE));
  $output .= drupal_get_form('vmember_topup_myaccount_form');
  return $output;
}


function vmobile_form_overview() {
						      
  if (empty($_SESSION['vmobile_search_filter'])) {
    $_SESSION['vmobile_search_filter'] = '';
  }

  $form['search'] = array(
    '#type' => 'textfield',
    '#title' => 'Search',
    '#size' => 10,
    '#default_value' => $_SESSION['vmobile_search_filter']
  );
			
  $form['submit'] = array('#type' => 'submit', '#value' =>t('Filter'));
//  $form['#redirect'] = FALSE;

  return $form;
}


